### ISSUE TITLE
Not sure how to add a header condition...

### ISSUE THREAD

**Issue by tombet1** [codeaholicguy/fastify-response-caching#7]
Hello! Thank you for this pluggin, I found it very useful for my proyect.
I have a very basic question:
I'm not sure how to add a header condition. I am using json token in the header (in authorization), and I don't want it to be stored on the cache. Currently, when I send diferents json tokens in the request, it gives me the same response as the first request. It should verify the token in each diferent request.

This is the code I am using:
`const fastifyResponseCaching = require('fastify-response-caching')`
`fastify.register(fastifyResponseCaching, {ttl: 60000, headers: ['authorization']})`

Thanks a lot!

**Comment by codeaholicguy** [comment]
Hi @tombet1, thank you for your feeback.
The `headers` config is for caching the requests which has the configured headers.

For example:
You config the plugin like this
```js
instance.register(plugin, {
  additionalCondition: {
    headers: ['x-should-applied'],
  },
})
```
You fire the request like this
```js
get(address, {
  headers: {'x-should-applied': 'yes'},
}), // req 1
get(address, {
  headers: {'x-should-applied': 'yes'},
}), // req 2
get(address, {
  headers: {'x-should-applied': 'no'},
}), // req 3
get(address), // req 4
```
The `req 2` will be get from cache, the `req 3`, `req 4` will skip the cache due to the header name and value are not matched.

For more information, could you please share the `cURL` or something similar?

**Comment by tombet1** [comment]
> Hi @tombet1, thank you for your feeback.
> The `headers` config is for caching the requests which has the configured headers.
> 
> For example:
> You config the plugin like this
> 
> ```js
> instance.register(plugin, {
>   additionalCondition: {
>     headers: ['x-should-applied'],
>   },
> })
> ```
> 
> You fire the request like this
> 
> ```js
> get(address, {
>   headers: {'x-should-applied': 'yes'},
> }), // req 1
> get(address, {
>   headers: {'x-should-applied': 'yes'},
> }), // req 2
> get(address, {
>   headers: {'x-should-applied': 'no'},
> }), // req 3
> get(address), // req 4
> ```
> 
> The `req 2` will be get from cache, the `req 3`, `req 4` will skip the cache due to the header name and value are not matched.
> 
> For more information, could you please share the `cURL` or something similar?

I will give it a try! Thanks!
